// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdiul-v2hQB3beafDCAfclxDEyJ32vLcU',
    appId: '1:463742409881:web:dc9aee17f2cd19a038ac08',
    messagingSenderId: '463742409881',
    projectId: 'noteapk-4f5da',
    authDomain: 'noteapk-4f5da.firebaseapp.com',
    storageBucket: 'noteapk-4f5da.appspot.com',
    measurementId: 'G-77W515QSWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMZt7jmQhJa7fDiq0ayma8xE3UWe_5ajs',
    appId: '1:463742409881:android:823bf9ff875cf55938ac08',
    messagingSenderId: '463742409881',
    projectId: 'noteapk-4f5da',
    storageBucket: 'noteapk-4f5da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HTBch86pwhpLFteLp6s1svtywCoxhvU',
    appId: '1:463742409881:ios:290fb2f132e47a3c38ac08',
    messagingSenderId: '463742409881',
    projectId: 'noteapk-4f5da',
    storageBucket: 'noteapk-4f5da.appspot.com',
    iosBundleId: 'com.example.firebaseSecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_HTBch86pwhpLFteLp6s1svtywCoxhvU',
    appId: '1:463742409881:ios:290fb2f132e47a3c38ac08',
    messagingSenderId: '463742409881',
    projectId: 'noteapk-4f5da',
    storageBucket: 'noteapk-4f5da.appspot.com',
    iosBundleId: 'com.example.firebaseSecond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdiul-v2hQB3beafDCAfclxDEyJ32vLcU',
    appId: '1:463742409881:web:f42e61933551f9e738ac08',
    messagingSenderId: '463742409881',
    projectId: 'noteapk-4f5da',
    authDomain: 'noteapk-4f5da.firebaseapp.com',
    storageBucket: 'noteapk-4f5da.appspot.com',
    measurementId: 'G-106LMNG2NL',
  );
}
